export const IMAGES = {
    tagaytay: {
        main: "/aklan",
        images: {
            taal_volcano: [
                '/TAGAYTAY/Taal Volcano/1.webp',
                '/TAGAYTAY/Taal Volcano/2.webp',
                '/TAGAYTAY/Taal Volcano/3.webp',
                '/TAGAYTAY/Taal Volcano/4.jpg',
            ],
            sky_ranch: [
                '/TAGAYTAY/Sky Ranch/1.jpg',
                '/TAGAYTAY/Sky Ranch/2.webp',
                '/TAGAYTAY/Sky Ranch/3.webp',
                '/TAGAYTAY/Sky Ranch/4.webp',
                '/TAGAYTAY/Sky Ranch/5.webp',
            ],
            picnic_grove: [
                '/TAGAYTAY/Picnic Grove/1.webp',
                '/TAGAYTAY/Picnic Grove/2.webp',
                '/TAGAYTAY/Picnic Grove/3.webp',
                '/TAGAYTAY/Picnic Grove/4.webp',
                '/TAGAYTAY/Picnic Grove/5.jpg',
            ],
            museo_orlina: [
                '/TAGAYTAY/Museo Orlina/1.jpg',
                '/TAGAYTAY/Museo Orlina/2.webp',
                '/TAGAYTAY/Museo Orlina/3.webp',
                '/TAGAYTAY/Museo Orlina/4.webp',
                '/TAGAYTAY/Museo Orlina/5.webp',
            ],
            mahogany_market: [
                '/TAGAYTAY/Mahogany Market/1.webp',
                '/TAGAYTAY/Mahogany Market/2.jpg',
                '/TAGAYTAY/Mahogany Market/3.webp',
                '/TAGAYTAY/Mahogany Market/4.jpeg',
            ],
        },
    },
    vigan: {
        main: "/aklan",
        images: {
            calle_crisologo: [
                '/VIGAN/CALLE CRISOLOGO/1.jpg',
                '/VIGAN/CALLE CRISOLOGO/2.jpg',
                '/VIGAN/CALLE CRISOLOGO/3.jpg',
                '/VIGAN/CALLE CRISOLOGO/4.jpg',
                '/VIGAN/CALLE CRISOLOGO/5.jpg',
                '/VIGAN/CALLE CRISOLOGO/6.jpg',
                '/VIGAN/CALLE CRISOLOGO/7.jpg',
                '/VIGAN/CALLE CRISOLOGO/8.jpg',
                '/VIGAN/CALLE CRISOLOGO/9.jpg',
                '/VIGAN/CALLE CRISOLOGO/10.jpg',
            ],
            plaza_salcedo: [
                '/VIGAN/PLAZA SALCEDO/1.jpg',
                '/VIGAN/PLAZA SALCEDO/2.jpg',
                '/VIGAN/PLAZA SALCEDO/3.jpg',
                '/VIGAN/PLAZA SALCEDO/4.jpg',
                '/VIGAN/PLAZA SALCEDO/5.jpg',
                '/VIGAN/PLAZA SALCEDO/6.jpg',
                '/VIGAN/PLAZA SALCEDO/7.jpg',
                '/VIGAN/PLAZA SALCEDO/8.jpg',
                '/VIGAN/PLAZA SALCEDO/9.jpg',
                '/VIGAN/PLAZA SALCEDO/10.jpg',
            ],
            saint_paul: [
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/1.jpg',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/2.jpg',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/3.jpg',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/4.jpg',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/5.jpg',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/6.jpg',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/7.jpg',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/8.jpg',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/9.jpg',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/10.jpg',
            ],
            bell_tower: [
                '/VIGAN/BANTAY BELL TOWER/1.jpg',
                '/VIGAN/BANTAY BELL TOWER/2.jpg',
                '/VIGAN/BANTAY BELL TOWER/3.jpg',
                '/VIGAN/BANTAY BELL TOWER/4.jpg',
                '/VIGAN/BANTAY BELL TOWER/5.jpg',
                '/VIGAN/BANTAY BELL TOWER/6.jpg',
                '/VIGAN/BANTAY BELL TOWER/7.jpg',
                '/VIGAN/BANTAY BELL TOWER/8.jpg',
                '/VIGAN/BANTAY BELL TOWER/9.jpg',
                '/VIGAN/BANTAY BELL TOWER/10.jpg',
            ],
            jar_factory: [
                '/VIGAN/PAGBURNAYAN JAR FACTORY/1.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/2.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/3.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/4.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/5.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/6.jpg',
            ],
            baluarte_zoo: [
                '/VIGAN/BALUARTE ZOO/1.jpg',
                '/VIGAN/BALUARTE ZOO/2.jpg',
                '/VIGAN/BALUARTE ZOO/3.jpg',
                '/VIGAN/BALUARTE ZOO/4.jpg',
                '/VIGAN/BALUARTE ZOO/5.jpg',
                '/VIGAN/BALUARTE ZOO/6.jpg',
                '/VIGAN/BALUARTE ZOO/7.webp',
                '/VIGAN/BALUARTE ZOO/8.jpg',
                '/VIGAN/BALUARTE ZOO/9.jpg',
                '/VIGAN/BALUARTE ZOO/10.jpg',
            ],
            kalesa: [
                '/VIGAN/RIDE A KALESA/1.jpg',
                '/VIGAN/RIDE A KALESA/2.jpg',
                '/VIGAN/RIDE A KALESA/3.jpg',
                '/VIGAN/RIDE A KALESA/4.jpg',
                '/VIGAN/RIDE A KALESA/5.jpg',
                '/VIGAN/RIDE A KALESA/6.jpg',
                '/VIGAN/RIDE A KALESA/7.jpg',
                '/VIGAN/RIDE A KALESA/8.jpg',
                '/VIGAN/RIDE A KALESA/9.jpg',
                '/VIGAN/RIDE A KALESA/10.jpg',
            ],
            local_cuisine: [
                '/VIGAN/FOOD-LOCAL CUISINE/1.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/2.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/3.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/4.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/5.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/6.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/7.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/8.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/9.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/10.jpg',
            ],
        },
    },
    aklan: {
        main: "/aklan",
        images: {
            bakhawan_park: [
                '/AKLAN/BAKHAWAN ECO-PARK/BAKHAWAN ECO-PARK(1).jpg',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKHAWAN ECO-PARK(2).jpg',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKHAWAN ECO-PARK(3).jpg',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKHAWAN ECO-PARK(4).jpg',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKHAWAN ECO-PARK(5).jpg',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKHAWAN ECO-PARK(6).webp'
            ],
            boracay: [
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(1).jpg',
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(2).jpg',
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(3).jpg',
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(4).jpg',
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(5).jpg',
            ],
            jawili_falls: [
                '/AKLAN/JAWILI FALLS/JAWILI FALLS_(1).png',
                '/AKLAN/JAWILI FALLS/JAWILI FALLS_(2).png',
                '/AKLAN/JAWILI FALLS/JAWILI FALLS_(3).png',
                '/AKLAN/JAWILI FALLS/JAWILI FALLS_(4).png',
                '/AKLAN/JAWILI FALLS/JAWILI FALLS_(5).jpg',
                '/AKLAN/JAWILI FALLS/JAWILI FALLS_(6).png',
            ],
            hurom_hurom: [
                '/AKLAN/HUROM HUROM COLD SPRING/HUROM HUROM COLD SPRING_(1).jpg',
                '/AKLAN/HUROM HUROM COLD SPRING/HUROM HUROM COLD SPRING_(2).jpg',
                '/AKLAN/HUROM HUROM COLD SPRING/HUROM HUROM COLD SPRING_(3).jpg',
                '/AKLAN/HUROM HUROM COLD SPRING/HUROM HUROM COLD SPRING_(4).jpg',
                '/AKLAN/HUROM HUROM COLD SPRING/HUROM HUROM COLD SPRING_(5).jpg',
            ],
            likitinon_rocks: [
                '/AKLAN/LIKITINON WHITE ROCKS/LIKITINON WHITE ROCKS_(1).webp',
                '/AKLAN/LIKITINON WHITE ROCKS/LIKITINON WHITE ROCKS_(2).webp',
                '/AKLAN/LIKITINON WHITE ROCKS/LIKITINON WHITE ROCKS_(3).webp',
                '/AKLAN/LIKITINON WHITE ROCKS/LIKITINON WHITE ROCKS_(4).webp',
                '/AKLAN/LIKITINON WHITE ROCKS/LIKITINON WHITE ROCKS_(5).webp',
                '/AKLAN/LIKITINON WHITE ROCKS/LIKITINON WHITE ROCKS_(6).jpg',
            ],
            pagatpat_park: [
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(1).jpg',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(2).jpg',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(3).png',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(4).png',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(5).jpg',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(6).png',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(7).png',
            ],
            hacienda_maria: [
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(1).png',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(2).png',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(3).png',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(4).png',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(5).png',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(6).webp',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(7).jpg',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(8).png',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(9).webp',
            ],
            hinugtan_beach: [
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(1).jpg',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(2).jpg',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(3).jpg',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(4).jpg',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(5).webp',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(6).jpg',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(7).webp',
            ],
            northwest_panay: [
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(1).jpg',
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(2).jpg',
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(3).jpg',
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(4).jpg',
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(5).jpg',
            ],
        },
    },
    ilocos_norte: {
        main: "/aklan",
        images: {
            paoay_church: [
                '/ILOCOS NORTE/PAOAY CHURCH/1.jpg',
                '/ILOCOS NORTE/PAOAY CHURCH/2.jpg',
                '/ILOCOS NORTE/PAOAY CHURCH/3.jpg',
                '/ILOCOS NORTE/PAOAY CHURCH/4.jpg',
                '/ILOCOS NORTE/PAOAY CHURCH/5.jpg',
                '/ILOCOS NORTE/PAOAY CHURCH/6.jpg',
                '/ILOCOS NORTE/PAOAY CHURCH/7.jpg',
                '/ILOCOS NORTE/PAOAY CHURCH/8.jpg',
                '/ILOCOS NORTE/PAOAY CHURCH/9.jpg',
                '/ILOCOS NORTE/PAOAY CHURCH/10.jpg',
            ],
            windmills: [
                '/ILOCOS NORTE/BANGUI WINDMILLS/1.jpg',
                '/ILOCOS NORTE/BANGUI WINDMILLS/2.jpg',
                '/ILOCOS NORTE/BANGUI WINDMILLS/3.jpg',
                '/ILOCOS NORTE/BANGUI WINDMILLS/4.jpg',
                '/ILOCOS NORTE/BANGUI WINDMILLS/5.jpg',
                '/ILOCOS NORTE/BANGUI WINDMILLS/6.jpg',
                '/ILOCOS NORTE/BANGUI WINDMILLS/7.jpg',
                '/ILOCOS NORTE/BANGUI WINDMILLS/8.jpg',
                '/ILOCOS NORTE/BANGUI WINDMILLS/9.jpg',
                '/ILOCOS NORTE/BANGUI WINDMILLS/10.jpg',
            ],
            kapurpurawan_formation: [
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/1.jpg',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/2.jpg',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/3.jpg',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/4.jpg',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/5.jpg',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/6.jpg',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/7.jpg',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/8.jpg',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/9.jpg',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/10.jpg',
            ],
            sand_dunes: [
                '/ILOCOS NORTE/PAOAY SAND DUNES/1.jpg',
                '/ILOCOS NORTE/PAOAY SAND DUNES/2.jpg',
                '/ILOCOS NORTE/PAOAY SAND DUNES/3.jpg',
                '/ILOCOS NORTE/PAOAY SAND DUNES/4.jpg',
                '/ILOCOS NORTE/PAOAY SAND DUNES/5.jpg',
                '/ILOCOS NORTE/PAOAY SAND DUNES/6.jpg',
                '/ILOCOS NORTE/PAOAY SAND DUNES/7.jpg',
                '/ILOCOS NORTE/PAOAY SAND DUNES/8.jpg',
                '/ILOCOS NORTE/PAOAY SAND DUNES/9.jpg',
                '/ILOCOS NORTE/PAOAY SAND DUNES/10.jpg',
            ],
            bojeador_lighthouse: [
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/1.jpg',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/2.jpg',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/3.jpg',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/4.jpg',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/5.jpg',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/6.jpg',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/7.jpg',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/8.jpg',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/9.jpg',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/10.jpg',
            ],
            patpat_viaduct: [
                '/ILOCOS NORTE/PATAPAT VIADUCT/1.jpg',
                '/ILOCOS NORTE/PATAPAT VIADUCT/2.jpg',
                '/ILOCOS NORTE/PATAPAT VIADUCT/3.jpg',
                '/ILOCOS NORTE/PATAPAT VIADUCT/4.jpg',
                '/ILOCOS NORTE/PATAPAT VIADUCT/5.jpg',
                '/ILOCOS NORTE/PATAPAT VIADUCT/6.jpg',
                '/ILOCOS NORTE/PATAPAT VIADUCT/7.jpg',
                '/ILOCOS NORTE/PATAPAT VIADUCT/8.jpg',
                '/ILOCOS NORTE/PATAPAT VIADUCT/9.jpg',
                '/ILOCOS NORTE/PATAPAT VIADUCT/10.jpg',
            ],
        },
    },
    ilocos_sur: {
        main: "/aklan",
        images: {
            sta_maria_church: [
                '/ILOCOS SUR/SANTA MARIA CHURCH/1.jpg',
                '/ILOCOS SUR/SANTA MARIA CHURCH/2.jpg',
                '/ILOCOS SUR/SANTA MARIA CHURCH/3.jpg',
                '/ILOCOS SUR/SANTA MARIA CHURCH/4.jpg',
                '/ILOCOS SUR/SANTA MARIA CHURCH/5.jpg',
                '/ILOCOS SUR/SANTA MARIA CHURCH/6.jpg',
                '/ILOCOS SUR/SANTA MARIA CHURCH/7.jpg',
                '/ILOCOS SUR/SANTA MARIA CHURCH/8.jpg',
                '/ILOCOS SUR/SANTA MARIA CHURCH/9.jpg',
                '/ILOCOS SUR/SANTA MARIA CHURCH/10.jpg',
            ],
            pinsall_falls: [
                '/ILOCOS SUR/PINSAL FALLS/1.jpg',
                '/ILOCOS SUR/PINSAL FALLS/2.jpg',
                '/ILOCOS SUR/PINSAL FALLS/3.jpg',
                '/ILOCOS SUR/PINSAL FALLS/4.jpg',
                '/ILOCOS SUR/PINSAL FALLS/5.jpg',
                '/ILOCOS SUR/PINSAL FALLS/6.jpg',
                '/ILOCOS SUR/PINSAL FALLS/7.jpg',
                '/ILOCOS SUR/PINSAL FALLS/8.jpg',
                '/ILOCOS SUR/PINSAL FALLS/9.jpg',
                '/ILOCOS SUR/PINSAL FALLS/10.jpg',
            ],
            provincial_capitol: [
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/1.jpg',
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/2.jpg',
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/3.jpg',
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/4.jpg',
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/5.jpg',
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/6.jpg',
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/7.jpg',
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/8.jpg',
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/9.jpg',
                '/ILOCOS SUR/ILOCOS SUR PROVINCIAL CAPITOL/10.jpg',
            ],
        },
    },
    cebu: {
        main: "/aklan",
        images: {
            magellan_cross: [
                '/CEBU/Magellan_s Cross/1.jpeg',
                '/CEBU/Magellan_s Cross/2.webp',
                '/CEBU/Magellan_s Cross/3.jpg',
                '/CEBU/Magellan_s Cross/4.webp',
                '/CEBU/Magellan_s Cross/5.webp',
                '/CEBU/Magellan_s Cross/6.webp',
            ],
            kawasan_falls: [
                '/CEBU/Kawasan Falls/1.jpg',
                '/CEBU/Kawasan Falls/2.webp',
                '/CEBU/Kawasan Falls/3.webp',
                '/CEBU/Kawasan Falls/4.webp',
                '/CEBU/Kawasan Falls/5.webp',
                '/CEBU/Kawasan Falls/6.webp',
            ],
            oslob_whale: [
                '/CEBU/Oslob Whale Shark/1.webp',
                '/CEBU/Oslob Whale Shark/2.webp',
                '/CEBU/Oslob Whale Shark/3.webp',
                '/CEBU/Oslob Whale Shark/4.webp',
                '/CEBU/Oslob Whale Shark/5.webp',
                '/CEBU/Oslob Whale Shark/6.webp',
            ],
            fort_san_pedro: [
                '/CEBU/Fort San Pedro/1.webp',
                '/CEBU/Fort San Pedro/2.jpg',
                '/CEBU/Fort San Pedro/3.jpg',
                '/CEBU/Fort San Pedro/4.jpg',
                '/CEBU/Fort San Pedro/5.webp',
            ],
            simala_shrine: [
                '/CEBU/Simala Shrine/1.jpg',
                '/CEBU/Simala Shrine/2.webp',
                '/CEBU/Simala Shrine/3.jpeg',
                '/CEBU/Simala Shrine/4.jpeg',
                '/CEBU/Simala Shrine/5.webp',
                '/CEBU/Simala Shrine/6.jpg',
            ],
            temple_leah: [
                '',
            ],
            sirao_garden: [
                '/CEBU/Sirao Flower Garden/1.jpg',
                '/CEBU/Sirao Flower Garden/2.jpg',
                '/CEBU/Sirao Flower Garden/3.jpg',
                '/CEBU/Sirao Flower Garden/4.jpg',
                '/CEBU/Sirao Flower Garden/5.jpg',
                '/CEBU/Sirao Flower Garden/6.jpg',
                '/CEBU/Sirao Flower Garden/7.jpg',
            ],
        },
    },
    la_union: {
        main: "/aklan",
        images: {
            bahay_bato: [
                '/LA UNION/BAHAY NA BATO/1.jpg',
                '/LA UNION/BAHAY NA BATO/2.webp',
                '/LA UNION/BAHAY NA BATO/3.jpg',
                '/LA UNION/BAHAY NA BATO/4.webp',
                '/LA UNION/BAHAY NA BATO/5.jpg',
                '/LA UNION/BAHAY NA BATO/6.png',
                '/LA UNION/BAHAY NA BATO/7.webp',
            ],
            bulalakaw_falls: [
                '/LA UNION/BULALAKAW FALLS/1.jpg',
                '/LA UNION/BULALAKAW FALLS/2.jpg',
                '/LA UNION/BULALAKAW FALLS/3.jpg',
                '/LA UNION/BULALAKAW FALLS/4.jpg',
                '/LA UNION/BULALAKAW FALLS/5.jpg',
                '/LA UNION/BULALAKAW FALLS/6.jpg',
                '/LA UNION/BULALAKAW FALLS/7.jpg',
            ],
            lotus_valley: [
                '/LA UNION/LOTUS VALLEY FARM/1.jpg',
                '/LA UNION/LOTUS VALLEY FARM/2.jpg',
                '/LA UNION/LOTUS VALLEY FARM/3.jpg',
            ],
            poro_lighthouse: [
                '/LA UNION/PORO POINT LIGHTHOUSE/1.jpg',
                '/LA UNION/PORO POINT LIGHTHOUSE/2.jpg',
                '/LA UNION/PORO POINT LIGHTHOUSE/3.jpg',
                '/LA UNION/PORO POINT LIGHTHOUSE/4.jpg',
                '/LA UNION/PORO POINT LIGHTHOUSE/5.jpg',
                '/LA UNION/PORO POINT LIGHTHOUSE/6.webp',
            ],
            urbiztondo_beach: [
                '/LA UNION/URBIZTONDO BEACH/1.jpg',
                '/LA UNION/URBIZTONDO BEACH/2.jpg',
                '/LA UNION/URBIZTONDO BEACH/3.jpg',
                '/LA UNION/URBIZTONDO BEACH/4.jpg',
                '/LA UNION/URBIZTONDO BEACH/5.jpg',
                '/LA UNION/URBIZTONDO BEACH/6.jpg',
                '/LA UNION/URBIZTONDO BEACH/7.jpg',
                '/LA UNION/URBIZTONDO BEACH/8.jpg',
                '/LA UNION/URBIZTONDO BEACH/9.jpg',
                '/LA UNION/URBIZTONDO BEACH/10.jpg',
            ],
            watch_tower: [
                '/LA UNION/BALUARTE WATCH TOWER/1.jpg',
                '/LA UNION/BALUARTE WATCH TOWER/2.png',
                '/LA UNION/BALUARTE WATCH TOWER/3.webp',
                '/LA UNION/BALUARTE WATCH TOWER/4.jpg',
                '/LA UNION/BALUARTE WATCH TOWER/5.png',
                '/LA UNION/BALUARTE WATCH TOWER/6.webp',
            ],
            immuki_island: [
                '/LA UNION/IMMUKI ISLAND/1.jpg',
                '/LA UNION/IMMUKI ISLAND/2.webp',
                '/LA UNION/IMMUKI ISLAND/3.jpg',
                '/LA UNION/IMMUKI ISLAND/4.webp',
                '/LA UNION/IMMUKI ISLAND/5.jpg',
                '/LA UNION/IMMUKI ISLAND/6.jpg',
                '/LA UNION/IMMUKI ISLAND/7.webp',
            ],
            macho_temple: [
                '/LA UNION/MA-CHO TEMPLE/1.jpg',
                '/LA UNION/MA-CHO TEMPLE/2.jpg',
                '/LA UNION/MA-CHO TEMPLE/3.jpg',
                '/LA UNION/MA-CHO TEMPLE/4.jpg',
                '/LA UNION/MA-CHO TEMPLE/5.jpg',
                '/LA UNION/MA-CHO TEMPLE/6.jpg',
                '/LA UNION/MA-CHO TEMPLE/7.jpg',
            ],
            tangadan_falls: [
                '/LA UNION/TANGADAN FALLS/1.jpg',
                '/LA UNION/TANGADAN FALLS/2.jpg',
                '/LA UNION/TANGADAN FALLS/3.jpg',
                '/LA UNION/TANGADAN FALLS/4.jpg',
                '/LA UNION/TANGADAN FALLS/5.jpg',
                '/LA UNION/TANGADAN FALLS/6.jpg',
                '/LA UNION/TANGADAN FALLS/7.jpg',
                '/LA UNION/TANGADAN FALLS/8.webp',
            ],
            pebble_beach: [
                '/LA UNION/PEBBLE BEACH/1.jpg',
                '/LA UNION/PEBBLE BEACH/2.jpg',
                '/LA UNION/PEBBLE BEACH/3.jpg',
                '/LA UNION/PEBBLE BEACH/4.jpg',
                '/LA UNION/PEBBLE BEACH/5.webp',
                '/LA UNION/PEBBLE BEACH/6.jpg',
            ],
        },
    },
    davao: {
        main: "/aklan",
        images: {
            eden_park: [
                '/DAVAO/Eden Garden/1.webp',
                '/DAVAO/Eden Garden/2.jpg',
                '/DAVAO/Eden Garden/3.jpg',
                '/DAVAO/Eden Garden/4.jpg',
                '/DAVAO/Eden Garden/5.jpg',
                '/DAVAO/Eden Garden/6.webp',
                '/DAVAO/Eden Garden/7.jpg',
                '/DAVAO/Eden Garden/8.jpg',
                '/DAVAO/Eden Garden/9.jpg',
                '/DAVAO/Eden Garden/10.jpg',
            ],
            eagle_center: [
                '/DAVAO/Philippine Eagle Center/1.jpg',
                '/DAVAO/Philippine Eagle Center/2.webp',
                '/DAVAO/Philippine Eagle Center/3.webp',
                '/DAVAO/Philippine Eagle Center/4.webp',
                '/DAVAO/Philippine Eagle Center/5.jpg',
            ],
            people_park: [
                '/DAVAO/People_s Park/1.jpg',
                '/DAVAO/People_s Park/2.jpeg',
                '/DAVAO/People_s Park/3.webp',
                '/DAVAO/People_s Park/4.webp',
                '/DAVAO/People_s Park/5.webp',
                '/DAVAO/People_s Park/6.webp',
                '/DAVAO/People_s Park/7.webp',
                '/DAVAO/People_s Park/8.jpeg',
            ],
            jack_ridge: [
                '/DAVAO/Jack_s Ridge/1.jpg',
                '/DAVAO/Jack_s Ridge/2.jpg',
                '/DAVAO/Jack_s Ridge/3.jpg',
                '/DAVAO/Jack_s Ridge/4.webp',
                '/DAVAO/Jack_s Ridge/5.webp',
            ],
            crocodile_park: [
                '/DAVAO/Crocodile_s Park/1.jpg',
                '/DAVAO/Crocodile_s Park/2.webp',
                '/DAVAO/Crocodile_s Park/3.jpg',
                '/DAVAO/Crocodile_s Park/4.webp',
                '/DAVAO/Crocodile_s Park/5.webp',
            ],
        },
    },
    palawan: {
        main: "/aklan",
        images: {
            puerto_princesa: [
                '/PALAWAN/Puerto Princesa/1.jpg',
                '/PALAWAN/Puerto Princesa/2.webp',
                '/PALAWAN/Puerto Princesa/3.webp',
                '/PALAWAN/Puerto Princesa/4.webp',
                '/PALAWAN/Puerto Princesa/5.webp',
                '/PALAWAN/Puerto Princesa/6.webp',
                '/PALAWAN/Puerto Princesa/7.webp',
            ],
            island_hopping: [
                '/PALAWAN/El Nido/1.webp',
                '/PALAWAN/El Nido/2.jpg',
                '/PALAWAN/El Nido/3.jpg',
                '/PALAWAN/El Nido/4.webp',
                '/PALAWAN/El Nido/5.webp',
            ],
            coron_shipwreck: [
                '/PALAWAN/Coron Ship Wreck/1.jpg',
                '/PALAWAN/Coron Ship Wreck/2.jpeg',
                '/PALAWAN/Coron Ship Wreck/3.webpq',
                '/PALAWAN/Coron Ship Wreck/4.webpq',
            ],
            honda_bay: [
                '/PALAWAN/Honda Bay/1.jpg',
                '/PALAWAN/Honda Bay/2.jpg',
                '/PALAWAN/Honda Bay/3.jpg',
                '/PALAWAN/Honda Bay/4.webp',
                '/PALAWAN/Honda Bay/5.webp',
            ],
            nacpan_beach: [
                '/PALAWAN/Nacpan Beach/1.jpg',
                '/PALAWAN/Nacpan Beach/2.webp',
                '/PALAWAN/Nacpan Beach/3.webp',
                '/PALAWAN/Nacpan Beach/4.jpg',
                '/PALAWAN/Nacpan Beach/5.webp',
                '/PALAWAN/Nacpan Beach/6.webp',
                '/PALAWAN/Nacpan Beach/7.webp',
                '/PALAWAN/Nacpan Beach/8.webp',
            ],
        },
    },
    bukidnon: {
        main: "/aklan",
        images: {
            alalumm_falls: [
                '/BUKIDNON/ALALUM FALLS/1.jpg',
                '/BUKIDNON/ALALUM FALLS/2.jpg',
                '/BUKIDNON/ALALUM FALLS/3.jpg',
                '/BUKIDNON/ALALUM FALLS/4.jpg',
                '/BUKIDNON/ALALUM FALLS/5.jpg',
                '/BUKIDNON/ALALUM FALLS/6.jpg',
                '/BUKIDNON/ALALUM FALLS/7.jpg',
                '/BUKIDNON/ALALUM FALLS/8.jpg',
                '/BUKIDNON/ALALUM FALLS/9.jpg',
                '/BUKIDNON/ALALUM FALLS/10.jpg',
                '/BUKIDNON/ALALUM FALLS/11.jpg',
            ],
            cedar_falls: [
                '/BUKIDNON/CEDAR WATERFALLS/1.jpg',
                '/BUKIDNON/CEDAR WATERFALLS/2.webp',
                '/BUKIDNON/CEDAR WATERFALLS/3.jpg',
                '/BUKIDNON/CEDAR WATERFALLS/4.jpg',
                '/BUKIDNON/CEDAR WATERFALLS/5.jpg',
                '/BUKIDNON/CEDAR WATERFALLS/6.jpg',
                '/BUKIDNON/CEDAR WATERFALLS/7.jpg',
                '/BUKIDNON/CEDAR WATERFALLS/8.jpg',
                '/BUKIDNON/CEDAR WATERFALLS/9.jpg',
                '/BUKIDNON/CEDAR WATERFALLS/10.jpg',
                '/BUKIDNON/CEDAR WATERFALLS/11.webp',
            ],
            communal_ranch: [
                '/BUKIDNON/COMMUNAL RANCH/1.jpg',
                '/BUKIDNON/COMMUNAL RANCH/2.webp',
                '/BUKIDNON/COMMUNAL RANCH/3.jpg',
                '/BUKIDNON/COMMUNAL RANCH/4.webp',
                '/BUKIDNON/COMMUNAL RANCH/5.jpg',
                '/BUKIDNON/COMMUNAL RANCH/6.jpg',
                '/BUKIDNON/COMMUNAL RANCH/7.jpg',
                '/BUKIDNON/COMMUNAL RANCH/8.jpg',
                '/BUKIDNON/COMMUNAL RANCH/9.jpg',
                '/BUKIDNON/COMMUNAL RANCH/10.webp',
            ],
            dahilayan_park: [
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/1.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/2.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/3.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/4.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/5.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/6.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/7.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/8.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/9.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/10.jpg',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/11.webp',
            ],
            kaamulan_park: [
                '/BUKIDNON/KAAMULAN PARK/1.jpg',
                '/BUKIDNON/KAAMULAN PARK/2.jpg',
                '/BUKIDNON/KAAMULAN PARK/3.jpg',
                '/BUKIDNON/KAAMULAN PARK/4.jpg',
                '/BUKIDNON/KAAMULAN PARK/5.jpg',
                '/BUKIDNON/KAAMULAN PARK/6.jpg',
                '/BUKIDNON/KAAMULAN PARK/7.jpg',
                '/BUKIDNON/KAAMULAN PARK/8.jpg',
                '/BUKIDNON/KAAMULAN PARK/9.webp',
            ],
            lake_apo: [
                '/BUKIDNON/LAKE APO/1.jpg',
                '/BUKIDNON/LAKE APO/2.jpg',
                '/BUKIDNON/LAKE APO/3.jpg',
                '/BUKIDNON/LAKE APO/4.jpg',
                '/BUKIDNON/LAKE APO/5.jpg',
                '/BUKIDNON/LAKE APO/6.jpg',
                '/BUKIDNON/LAKE APO/7.jpg',
                '/BUKIDNON/LAKE APO/8.jpg',
                '/BUKIDNON/LAKE APO/9.jpg',
                '/BUKIDNON/LAKE APO/10.jpg',
                '/BUKIDNON/LAKE APO/11.jpg',
                '/BUKIDNON/LAKE APO/12.webp',
            ],
            monastery_transfiguration: [
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/1.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/2.webp',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/3.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/4.webp',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/5.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/6.webp',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/7.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/8.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/9.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/10.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/11.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/12.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/13.jpg',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/14.webp',
            ],
            mt_anahawon: [
                '/BUKIDNON/MT. ANAHAWON/1.jpg',
                '/BUKIDNON/MT. ANAHAWON/2.webp',
                '/BUKIDNON/MT. ANAHAWON/3.webp',
                '/BUKIDNON/MT. ANAHAWON/4.webp',
                '/BUKIDNON/MT. ANAHAWON/5.webp',
                '/BUKIDNON/MT. ANAHAWON/6.webp',
                '/BUKIDNON/MT. ANAHAWON/7.webp',
                '/BUKIDNON/MT. ANAHAWON/8.webp',
            ],
            nasuli_spring: [
                '/BUKIDNON/NASULI SPRING/1.jpg',
                '/BUKIDNON/NASULI SPRING/2.jpg',
                '/BUKIDNON/NASULI SPRING/3.jpg',
                '/BUKIDNON/NASULI SPRING/4.jpg',
                '/BUKIDNON/NASULI SPRING/5.jpg',
                '/BUKIDNON/NASULI SPRING/6.webp',
            ],
        },
    },
    boracay: {
        main: "/aklan",
        images: {
            ariel_point: [
                '/BORACAY/ARIEL_S POINT/1.jpg',
                '/BORACAY/ARIEL_S POINT/2.jpg',
                '/BORACAY/ARIEL_S POINT/3.jpg',
                '/BORACAY/ARIEL_S POINT/4.jpg',
                '/BORACAY/ARIEL_S POINT/5.jpg',
                '/BORACAY/ARIEL_S POINT/6.jpg',
                '/BORACAY/ARIEL_S POINT/7.png',
                '/BORACAY/ARIEL_S POINT/8.webp',
            ],
            bulabog_beach: [
                '/BORACAY/BULABOG BEACH/1.jpg',
                '/BORACAY/BULABOG BEACH/2.webp',
                '/BORACAY/BULABOG BEACH/3.jpg',
                '/BORACAY/BULABOG BEACH/4.webp',
                '/BORACAY/BULABOG BEACH/5.jpg',
                '/BORACAY/BULABOG BEACH/6.jpg',
                '/BORACAY/BULABOG BEACH/7.jpg',
                '/BORACAY/BULABOG BEACH/8.jpg',
                '/BORACAY/BULABOG BEACH/9.webp',
            ],
            crystal_cove: [
                '/BORACAY/CRYSTAL COVE ISLAND/1.jpg',
                '/BORACAY/CRYSTAL COVE ISLAND/2.jpg',
                '/BORACAY/CRYSTAL COVE ISLAND/3.jpg',
                '/BORACAY/CRYSTAL COVE ISLAND/4.jpg',
                '/BORACAY/CRYSTAL COVE ISLAND/5.jpg',
                '/BORACAY/CRYSTAL COVE ISLAND/6.jpg',
                '/BORACAY/CRYSTAL COVE ISLAND/7.jpg',
                '/BORACAY/CRYSTAL COVE ISLAND/8.webp',
            ],
            dmall_boracay: [
                '/BORACAY/D_MALL BORACAY/1.jpg',
                '/BORACAY/D_MALL BORACAY/2.jpg',
                '/BORACAY/D_MALL BORACAY/3.jpg',
                '/BORACAY/D_MALL BORACAY/4.jpg',
                '/BORACAY/D_MALL BORACAY/5.jpg',
                '/BORACAY/D_MALL BORACAY/6.jpg',
                '/BORACAY/D_MALL BORACAY/7.webp',
            ],
            paraw_sailing: [
                '/BORACAY/PARAW SAILING/1.jpg',
                '/BORACAY/PARAW SAILING/2.jpg',
                '/BORACAY/PARAW SAILING/3.jpg',
                '/BORACAY/PARAW SAILING/4.jpg',
                '/BORACAY/PARAW SAILING/5.jpg',
                '/BORACAY/PARAW SAILING/6.jpg',
                '/BORACAY/PARAW SAILING/7.jpg',
                '/BORACAY/PARAW SAILING/8.jpg',
            ],
            white_beach: [
                '/BORACAY/WHITE BEACH/1.jpg',
                '/BORACAY/WHITE BEACH/2.jpg',
                '/BORACAY/WHITE BEACH/3.jpg',
                '/BORACAY/WHITE BEACH/4.jpg',
                '/BORACAY/WHITE BEACH/5.jpg',
                '/BORACAY/WHITE BEACH/6.jpg',
                '/BORACAY/WHITE BEACH/7.jpg',
                '/BORACAY/WHITE BEACH/8.jpg',
                '/BORACAY/WHITE BEACH/9.webp',
            ],
            willys_rock: [
                '/BORACAY/WILLY_S ROCK/1.jpg',
                '/BORACAY/WILLY_S ROCK/2.jpg',
                '/BORACAY/WILLY_S ROCK/3.jpg',
                '/BORACAY/WILLY_S ROCK/4.jpg',
                '/BORACAY/WILLY_S ROCK/5.jpg',
                '/BORACAY/WILLY_S ROCK/6.jpg',
                '/BORACAY/WILLY_S ROCK/7.webp',
            ],
        },
    },
    camiguin: {
        main: "/aklan",
        images: {
            white_island: [
                '/CAMIGUIN/WHITE ISLAND/1.jpg',
                '/CAMIGUIN/WHITE ISLAND/2.jpg',
            ],
            katibawasan_falls: [
                '/CAMIGUIN/KATIBAWASAN FALLS/1.webp',
                '/CAMIGUIN/KATIBAWASAN FALLS/2.webp',
                '/CAMIGUIN/KATIBAWASAN FALLS/3.jpg',
                '/CAMIGUIN/KATIBAWASAN FALLS/4.jpg',
                '/CAMIGUIN/KATIBAWASAN FALLS/5.jpg',
                '/CAMIGUIN/KATIBAWASAN FALLS/6.jpg',
                '/CAMIGUIN/KATIBAWASAN FALLS/7.jpg',
                '/CAMIGUIN/KATIBAWASAN FALLS/8.jpg',
                '/CAMIGUIN/KATIBAWASAN FALLS/9.jpg',
            ],
            sunken_cemetery: [
                '/CAMIGUIN/SUNKEN CEMETERY/1.webp',
                '/CAMIGUIN/SUNKEN CEMETERY/2.webp',
                '/CAMIGUIN/SUNKEN CEMETERY/3.webp',
                '/CAMIGUIN/SUNKEN CEMETERY/4.webp',
                '/CAMIGUIN/SUNKEN CEMETERY/5.webp',
                '/CAMIGUIN/SUNKEN CEMETERY/6.webp',
                '/CAMIGUIN/SUNKEN CEMETERY/7.webp',
                '/CAMIGUIN/SUNKEN CEMETERY/8.webp',
                '/CAMIGUIN/SUNKEN CEMETERY/9.jpg',
                '/CAMIGUIN/SUNKEN CEMETERY/10.webp',
            ],
            mantigue_island: [
                '/CAMIGUIN/MANTIGUE ISLAND/1.jpg',
                '/CAMIGUIN/MANTIGUE ISLAND/2.jpg',
                '/CAMIGUIN/MANTIGUE ISLAND/3.jpg',
                '/CAMIGUIN/MANTIGUE ISLAND/4.jpg',
                '/CAMIGUIN/MANTIGUE ISLAND/5.jpg',
                '/CAMIGUIN/MANTIGUE ISLAND/6.jpg',
                '/CAMIGUIN/MANTIGUE ISLAND/7.jpg',
                '/CAMIGUIN/MANTIGUE ISLAND/8.jpg',
                '/CAMIGUIN/MANTIGUE ISLAND/9.jpg',
            ],
            bura_water_park: [
                '/CAMIGUIN/BURA SODA WATER PARK/1.jpg',
                '/CAMIGUIN/BURA SODA WATER PARK/2.jpg',
                '/CAMIGUIN/BURA SODA WATER PARK/3.jpg',
                '/CAMIGUIN/BURA SODA WATER PARK/4.jpg',
                '/CAMIGUIN/BURA SODA WATER PARK/5.jpg',
                '/CAMIGUIN/BURA SODA WATER PARK/6.jpg',
                '/CAMIGUIN/BURA SODA WATER PARK/7.jpg',
            ],
            tanguines_lagoon: [
                '/CAMIGUIN/TAGUINES LAGOON/1.jpg',
                '/CAMIGUIN/TAGUINES LAGOON/2.webp',
                '/CAMIGUIN/TAGUINES LAGOON/3.jpg',
                '/CAMIGUIN/TAGUINES LAGOON/4.webp',
                '/CAMIGUIN/TAGUINES LAGOON/5.webp',
                '/CAMIGUIN/TAGUINES LAGOON/6.jpg',
                '/CAMIGUIN/TAGUINES LAGOON/7.webp',
            ],
        },
    },
    panabo: {
        main: "/aklan",
        images: {
            japanese_tunnel: [
                '/PANABO/JAPANESE TUNNEL/1.jpg',
                '/PANABO/JAPANESE TUNNEL/2.jpg',
                '/PANABO/JAPANESE TUNNEL/3.jpg',
                '/PANABO/JAPANESE TUNNEL/4.jpg',
                '/PANABO/JAPANESE TUNNEL/5.jpg',
                '/PANABO/JAPANESE TUNNEL/6.jpg',
                '/PANABO/JAPANESE TUNNEL/7.jpg',
                '/PANABO/JAPANESE TUNNEL/8.jpg',
            ],
            mangrove_forest: [
                '/PANABO/MANGROVE FOREST BOARDWALK/1.jpg',
                '/PANABO/MANGROVE FOREST BOARDWALK/2.jpg',
                '/PANABO/MANGROVE FOREST BOARDWALK/3.jpg',
                '/PANABO/MANGROVE FOREST BOARDWALK/4.jpg',
                '/PANABO/MANGROVE FOREST BOARDWALK/5.jpg',
                '/PANABO/MANGROVE FOREST BOARDWALK/6.jpg',
                '/PANABO/MANGROVE FOREST BOARDWALK/7.jpg',
                '/PANABO/MANGROVE FOREST BOARDWALK/8.jpg',
            ],
            seawall: [
                '/PANABO/SEAWALL/1.webp',
                '/PANABO/SEAWALL/2.webp',
                '/PANABO/SEAWALL/3.webp',
                '/PANABO/SEAWALL/4.webp',
                '/PANABO/SEAWALL/5.webp',
                '/PANABO/SEAWALL/6.webp',
                '/PANABO/SEAWALL/7.webp',
                '/PANABO/SEAWALL/8.webp',
                '/PANABO/SEAWALL/9.webp',
            ],
        },
    },
    tagum: {
        main: "/aklan",
        images: {
            botanical_park: [
                '/TAGUM/BOTANICAL PARK/1.jpg',
                '/TAGUM/BOTANICAL PARK/2.jpg',
                '/TAGUM/BOTANICAL PARK/3.jpg',
                '/TAGUM/BOTANICAL PARK/4.jpg',
                '/TAGUM/BOTANICAL PARK/5.jpg',
                '/TAGUM/BOTANICAL PARK/6.jpg',
                '/TAGUM/BOTANICAL PARK/7.jpg',
                '/TAGUM/BOTANICAL PARK/8.jpg',
                '/TAGUM/BOTANICAL PARK/9.jpg',
                '/TAGUM/BOTANICAL PARK/10.jpg',
                '/TAGUM/BOTANICAL PARK/11.jpg',
            ],
            banana_beach: [
                '/TAGUM/BANANA BEACH/1.jpg',
                '/TAGUM/BANANA BEACH/2.jpg',
                '/TAGUM/BANANA BEACH/3.jpg',
                '/TAGUM/BANANA BEACH/4.jpg',
                '/TAGUM/BANANA BEACH/5.jpg',
                '/TAGUM/BANANA BEACH/6.jpg',
            ],
            nabintad_cruise: [
                '/TAGUM/NABINTAD RIVER CRUISE/1.jpg',
                '/TAGUM/NABINTAD RIVER CRUISE/2.jpg',
                '/TAGUM/NABINTAD RIVER CRUISE/3.jpg',
                '/TAGUM/NABINTAD RIVER CRUISE/4.jpg',
                '/TAGUM/NABINTAD RIVER CRUISE/5.jpg',
                '/TAGUM/NABINTAD RIVER CRUISE/6.jpg',
                '/TAGUM/NABINTAD RIVER CRUISE/7.jpg',
                '/TAGUM/NABINTAD RIVER CRUISE/8.jpg',
            ],
        },
    },
}