export const IMAGES = {
    tagaytay: {
        main: "/aklan",
        images: {
            taal_volcano: [
                '/TAGAYTAY/Taal Volcano/1.webp',
                '/TAGAYTAY/Taal Volcano/2.webp',
                '/TAGAYTAY/Taal Volcano/3.webp',
                '/TAGAYTAY/Taal Volcano/4.jpg',
            ],
            sky_ranch: [
                '/TAGAYTAY/Sky Ranch/1.jpg',
                '/TAGAYTAY/Sky Ranch/2.webp',
                '/TAGAYTAY/Sky Ranch/3.webp',
                '/TAGAYTAY/Sky Ranch/4.webp',
                '/TAGAYTAY/Sky Ranch/5.webp',
            ],
            picnic_grove: [
                '/TAGAYTAY/Picnic Grove/1.webp',
                '/TAGAYTAY/Picnic Grove/2.webp',
                '/TAGAYTAY/Picnic Grove/3.webp',
                '/TAGAYTAY/Picnic Grove/4.webp',
                '/TAGAYTAY/Picnic Grove/5.jpg',
            ],
            museo_orlina: [
                '/TAGAYTAY/Museo Orlina/1.jpg',
                '/TAGAYTAY/Museo Orlina/2.webp',
                '/TAGAYTAY/Museo Orlina/3.webp',
                '/TAGAYTAY/Museo Orlina/4.webp',
                '/TAGAYTAY/Museo Orlina/5.webp',
            ],
            mahogany_market: [
                '/TAGAYTAY/Mahogany Market/1.webp',
                '/TAGAYTAY/Mahogany Market/2.jpg',
                '/TAGAYTAY/Mahogany Market/3.webp',
                '/TAGAYTAY/Mahogany Market/4.jpeg',
            ],
        },
    },
    vigan: {
        main: "/aklan",
        images: {
            calle_crisologo: [
                '/VIGAN/CALLE CRISOLOGO/1.jpg',
                '/VIGAN/CALLE CRISOLOGO/2.jpg',
                '/VIGAN/CALLE CRISOLOGO/3.jpg',
                '/VIGAN/CALLE CRISOLOGO/4.jpg',
                '/VIGAN/CALLE CRISOLOGO/5.jpg',
                '/VIGAN/CALLE CRISOLOGO/6.jpg',
                '/VIGAN/CALLE CRISOLOGO/7.jpg',
                '/VIGAN/CALLE CRISOLOGO/8.jpg',
                '/VIGAN/CALLE CRISOLOGO/9.jpg',
                '/VIGAN/CALLE CRISOLOGO/10.jpg',
            ],
            plaza_salcedo: [
                '/VIGAN/PLAZA SALCEDO/1.jpg',
                '/VIGAN/PLAZA SALCEDO/2.jpg',
                '/VIGAN/PLAZA SALCEDO/3.jpg',
                '/VIGAN/PLAZA SALCEDO/4.jpg',
                '/VIGAN/PLAZA SALCEDO/5.jpg',
                '/VIGAN/PLAZA SALCEDO/6.jpg',
                '/VIGAN/PLAZA SALCEDO/7.jpg',
                '/VIGAN/PLAZA SALCEDO/8.jpg',
                '/VIGAN/PLAZA SALCEDO/9.jpg',
                '/VIGAN/PLAZA SALCEDO/10.jpg',
            ],
            saint_paul: [
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/1',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/2',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/3',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/4',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/5',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/6',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/7',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/8',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/9',
                '/VIGAN/SAINT PAUL METROPOLITAN CATHEDRAL/10',
            ],
            bell_tower: [
                '/VIGAN/BELL TOWER/1.jpg',
                '/VIGAN/BELL TOWER/2.jpg',
                '/VIGAN/BELL TOWER/3.jpg',
                '/VIGAN/BELL TOWER/4.jpg',
                '/VIGAN/BELL TOWER/5.jpg',
                '/VIGAN/BELL TOWER/6.jpg',
                '/VIGAN/BELL TOWER/7.jpg',
                '/VIGAN/BELL TOWER/8.jpg',
                '/VIGAN/BELL TOWER/9.jpg',
                '/VIGAN/BELL TOWER/10.jpg',
            ],
            jar_factory: [
                '/VIGAN/PAGBURNAYAN JAR FACTORY/1.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/2.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/3.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/4.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/5.jpg',
                '/VIGAN/PAGBURNAYAN JAR FACTORY/6.jpg',
            ],
            baluarte_zoo: [
                '/VIGAN/BALUARTE ZOO/1.jpg',
                '/VIGAN/BALUARTE ZOO/2.jpg',
                '/VIGAN/BALUARTE ZOO/3.jpg',
                '/VIGAN/BALUARTE ZOO/4.jpg',
                '/VIGAN/BALUARTE ZOO/5.jpg',
                '/VIGAN/BALUARTE ZOO/6.jpg',
                '/VIGAN/BALUARTE ZOO/7.webp',
                '/VIGAN/BALUARTE ZOO/8.jpg',
                '/VIGAN/BALUARTE ZOO/9.jpg',
                '/VIGAN/BALUARTE ZOO/10.jpg',
            ],
            kalesa: [
                '/VIGAN/RIDE A KALESA/1.jpg',
                '/VIGAN/RIDE A KALESA/2.jpg',
                '/VIGAN/RIDE A KALESA/3.jpg',
                '/VIGAN/RIDE A KALESA/4.jpg',
                '/VIGAN/RIDE A KALESA/5.jpg',
                '/VIGAN/RIDE A KALESA/6.jpg',
                '/VIGAN/RIDE A KALESA/7.jpg',
                '/VIGAN/RIDE A KALESA/8.jpg',
                '/VIGAN/RIDE A KALESA/9.jpg',
                '/VIGAN/RIDE A KALESA/10.jpg',
            ],
            local_cuisine: [
                '/VIGAN/FOOD-LOCAL CUISINE/1.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/2.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/3.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/4.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/5.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/6.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/7.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/8.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/9.jpg',
                '/VIGAN/FOOD-LOCAL CUISINE/10.jpg',
            ],
        },
    },
    aklan: {
        main: "/aklan",
        images: {
            bakhawan_park: [
                '/AKLAN/BAKHAWAN ECO-PARK/BAKAWAN ECO PARK(1)',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKAWAN ECO PARK(2)',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKAWAN ECO PARK(3)',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKAWAN ECO PARK(4)',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKAWAN ECO PARK(5)',
                '/AKLAN/BAKHAWAN ECO-PARK/BAKAWAN ECO PARK(6)'
            ],
            boracay: [
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(1)',
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(2)',
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(3)',
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(4)',
                '/AKLAN/BORACAY ISLAND/BORACAY ISLAND_(5)',
            ],
            jawili_falls: [
                '/AKLAN/JAWILI FALSS/JAWILI FALSS_(1)',
                '/AKLAN/JAWILI FALSS/JAWILI FALSS_(2)',
                '/AKLAN/JAWILI FALSS/JAWILI FALSS_(3)',
                '/AKLAN/JAWILI FALSS/JAWILI FALSS_(4)',
                '/AKLAN/JAWILI FALSS/JAWILI FALSS_(5)',
                '/AKLAN/JAWILI FALSS/JAWILI FALSS_(6)',
            ],
            hurom_hurom: [
                '/AKLAN/HORUM HORUM COLD SPRING/HORUM HORUM COLD SPRING_(1)',
                '/AKLAN/HORUM HORUM COLD SPRING/HORUM HORUM COLD SPRING_(2)',
                '/AKLAN/HORUM HORUM COLD SPRING/HORUM HORUM COLD SPRING_(3)',
                '/AKLAN/HORUM HORUM COLD SPRING/HORUM HORUM COLD SPRING_(4)',
                '/AKLAN/HORUM HORUM COLD SPRING/HORUM HORUM COLD SPRING_(5)',
            ],
            likitinon_rocks: [
                '/AKLAN/LIKITON WHITE ROCKS/LIKITON WHITE ROCKS_(1)',
                '/AKLAN/LIKITON WHITE ROCKS/LIKITON WHITE ROCKS_(2)',
                '/AKLAN/LIKITON WHITE ROCKS/LIKITON WHITE ROCKS_(3)',
                '/AKLAN/LIKITON WHITE ROCKS/LIKITON WHITE ROCKS_(4)',
                '/AKLAN/LIKITON WHITE ROCKS/LIKITON WHITE ROCKS_(5)',
                '/AKLAN/LIKITON WHITE ROCKS/LIKITON WHITE ROCKS_(6)',
            ],
            pagatpat_park: [
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(1)',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(2)',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(3)',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(4)',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(5)',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(6)',
                '/AKLAN/PAGATPAT MANGROVE PARK/PAGATPAT MANGROVE PARK_(7)',
            ],
            hacienda_maria: [
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(1)',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(2)',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(3)',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(4)',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(5)',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(6)',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(7)',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(8)',
                '/AKLAN/HACIENDA MARIA/HACIENDA MARIA_(9)',
            ],
            hinugtan_beach: [
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(1)',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(2)',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(3)',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(4)',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(5)',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(6)',
                '/AKLAN/HINUGTAN BEACH/HINUGTAN BEACH_(7)',
            ],
            northwest_panay: [
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(1)',
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(2)',
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(3)',
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(4)',
                '/AKLAN/NORTHWEST PANAY PENINSULA NATURAL PARK/NORTHWEST PANAY PENINSULA NATURAL PARK_(5)',
            ],
        },
    },
    ilocos_norte: {
        main: "/aklan",
        images: {
            paoay_church: [
                '/ILOCOS NORTE/PAOAY SAND DUNES/1',
                '/ILOCOS NORTE/PAOAY SAND DUNES/2',
                '/ILOCOS NORTE/PAOAY SAND DUNES/3',
                '/ILOCOS NORTE/PAOAY SAND DUNES/4',
                '/ILOCOS NORTE/PAOAY SAND DUNES/5',
                '/ILOCOS NORTE/PAOAY SAND DUNES/6',
                '/ILOCOS NORTE/PAOAY SAND DUNES/7',
                '/ILOCOS NORTE/PAOAY SAND DUNES/8',
                '/ILOCOS NORTE/PAOAY SAND DUNES/9',
                '/ILOCOS NORTE/PAOAY SAND DUNES/10',
            ],
            windmills: [
                '/ILOCOS NORTE/BANGUI WINDMILLS/1',
                '/ILOCOS NORTE/BANGUI WINDMILLS/2',
                '/ILOCOS NORTE/BANGUI WINDMILLS/3',
                '/ILOCOS NORTE/BANGUI WINDMILLS/4',
                '/ILOCOS NORTE/BANGUI WINDMILLS/5',
                '/ILOCOS NORTE/BANGUI WINDMILLS/6',
                '/ILOCOS NORTE/BANGUI WINDMILLS/7',
                '/ILOCOS NORTE/BANGUI WINDMILLS/8',
                '/ILOCOS NORTE/BANGUI WINDMILLS/9',
                '/ILOCOS NORTE/BANGUI WINDMILLS/10',
            ],
            kapurpurawan_formation: [
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/1',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/2',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/3',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/4',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/5',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/6',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/7',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/8',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/9',
                '/ILOCOS NORTE/KAPURPURAWAN ROCK FORMATION/10',
            ],
            sand_dunes: [
                '/ILOCOS NORTE/PAOAY SAND DUNES/1',
                '/ILOCOS NORTE/PAOAY SAND DUNES/2',
                '/ILOCOS NORTE/PAOAY SAND DUNES/3',
                '/ILOCOS NORTE/PAOAY SAND DUNES/4',
                '/ILOCOS NORTE/PAOAY SAND DUNES/5',
                '/ILOCOS NORTE/PAOAY SAND DUNES/6',
                '/ILOCOS NORTE/PAOAY SAND DUNES/7',
                '/ILOCOS NORTE/PAOAY SAND DUNES/8',
                '/ILOCOS NORTE/PAOAY SAND DUNES/9',
                '/ILOCOS NORTE/PAOAY SAND DUNES/10',
            ],
            bojeador_lighthouse: [
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/1',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/2',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/3',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/4',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/5',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/6',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/7',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/8',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/9',
                '/ILOCOS NORTE/CAPE BOJEADOR LIGHTHOUSE/10',
            ],
            patpat_viaduct: [
                '/ILOCOS NORTE/PATPAT VIADUCT/1',
                '/ILOCOS NORTE/PATPAT VIADUCT/2',
                '/ILOCOS NORTE/PATPAT VIADUCT/3',
                '/ILOCOS NORTE/PATPAT VIADUCT/4',
                '/ILOCOS NORTE/PATPAT VIADUCT/5',
                '/ILOCOS NORTE/PATPAT VIADUCT/6',
                '/ILOCOS NORTE/PATPAT VIADUCT/7',
                '/ILOCOS NORTE/PATPAT VIADUCT/8',
                '/ILOCOS NORTE/PATPAT VIADUCT/9',
                '/ILOCOS NORTE/PATPAT VIADUCT/10',
            ],
        },
    },
    ilocos_sur: {
        main: "/aklan",
        images: {
            sta_maria_church: [
                '/ILOCOS NORTE/SANTA MARIA CHURCH/1',
                '/ILOCOS NORTE/SANTA MARIA CHURCH/2',
                '/ILOCOS NORTE/SANTA MARIA CHURCH/3',
                '/ILOCOS NORTE/SANTA MARIA CHURCH/4',
                '/ILOCOS NORTE/SANTA MARIA CHURCH/5',
                '/ILOCOS NORTE/SANTA MARIA CHURCH/6',
                '/ILOCOS NORTE/SANTA MARIA CHURCH/7',
                '/ILOCOS NORTE/SANTA MARIA CHURCH/8',
                '/ILOCOS NORTE/SANTA MARIA CHURCH/9',
                '/ILOCOS NORTE/SANTA MARIA CHURCH/10',
            ],
            pinsall_falls: [
                '/ILOCOS NORTE/PINSALL FALLS/1',
                '/ILOCOS NORTE/PINSALL FALLS/2',
                '/ILOCOS NORTE/PINSALL FALLS/3',
                '/ILOCOS NORTE/PINSALL FALLS/4',
                '/ILOCOS NORTE/PINSALL FALLS/5',
                '/ILOCOS NORTE/PINSALL FALLS/6',
                '/ILOCOS NORTE/PINSALL FALLS/7',
                '/ILOCOS NORTE/PINSALL FALLS/8',
                '/ILOCOS NORTE/PINSALL FALLS/9',
                '/ILOCOS NORTE/PINSALL FALLS/10',
            ],
            provincial_capitol: [
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/1',
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/2',
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/3',
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/4',
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/5',
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/6',
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/7',
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/8',
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/9',
                '/ILOCOS NORTE/ILOCOS SUR PROVINCIAL CAPITOL/10',
            ],
        },
    },
    cebu: {
        main: "/aklan",
        images: {
            magellan_cross: [
                '/CEBU/Magellan_s Cross/1',
                '/CEBU/Magellan_s Cross/2',
                '/CEBU/Magellan_s Cross/3',
                '/CEBU/Magellan_s Cross/4',
                '/CEBU/Magellan_s Cross/5',
                '/CEBU/Magellan_s Cross/6',
            ],
            kawasan_falls: [
                '/CEBU/Kawasan Falls/1',
                '/CEBU/Kawasan Falls/2',
                '/CEBU/Kawasan Falls/3',
                '/CEBU/Kawasan Falls/4',
                '/CEBU/Kawasan Falls/5',
                '/CEBU/Kawasan Falls/6',
            ],
            oslob_whale: [
                '/CEBU/Oslob Whale Shark/1',
                '/CEBU/Oslob Whale Shark/2',
                '/CEBU/Oslob Whale Shark/3',
                '/CEBU/Oslob Whale Shark/4',
                '/CEBU/Oslob Whale Shark/5',
                '/CEBU/Oslob Whale Shark/6',
            ],
            fort_san_pedro: [
                '/CEBU/Fort San Pedro/1',
                '/CEBU/Fort San Pedro/2',
                '/CEBU/Fort San Pedro/3',
                '/CEBU/Fort San Pedro/4',
                '/CEBU/Fort San Pedro/5',
            ],
            simala_shrine: [
                '/CEBU/Simala Shrine/1',
                '/CEBU/Simala Shrine/2',
                '/CEBU/Simala Shrine/3',
                '/CEBU/Simala Shrine/4',
                '/CEBU/Simala Shrine/5',
                '/CEBU/Simala Shrine/6',
            ],
            temple_leah: [
                '',
            ],
            sirao_garden: [
                '/CEBU/Sirao Flower Garden/1',
                '/CEBU/Sirao Flower Garden/2',
                '/CEBU/Sirao Flower Garden/3',
                '/CEBU/Sirao Flower Garden/4',
                '/CEBU/Sirao Flower Garden/5',
                '/CEBU/Sirao Flower Garden/6',
                '/CEBU/Sirao Flower Garden/7',
            ],
        },
    },
    la_union: {
        main: "/aklan",
        images: {
            bahay_bato: [
                '/LA UNION/BAHAY NA BATO/1',
                '/LA UNION/BAHAY NA BATO/2',
                '/LA UNION/BAHAY NA BATO/3',
                '/LA UNION/BAHAY NA BATO/4',
                '/LA UNION/BAHAY NA BATO/5',
                '/LA UNION/BAHAY NA BATO/6',
                '/LA UNION/BAHAY NA BATO/7',
            ],
            bulalakaw_falls: [
                '/LA UNION/BULALAKAW FALLS/1',
                '/LA UNION/BULALAKAW FALLS/2',
                '/LA UNION/BULALAKAW FALLS/3',
                '/LA UNION/BULALAKAW FALLS/4',
                '/LA UNION/BULALAKAW FALLS/5',
                '/LA UNION/BULALAKAW FALLS/6',
                '/LA UNION/BULALAKAW FALLS/7',
            ],
            lotus_valley: [
                '/LA UNION/LOTUS VALLEY FARM/1',
                '/LA UNION/LOTUS VALLEY FARM/2',
                '/LA UNION/LOTUS VALLEY FARM/3',
            ],
            poro_lighthouse: [
                '/LA UNION/PORO POINT LIGHTHOUSE/1',
                '/LA UNION/PORO POINT LIGHTHOUSE/2',
                '/LA UNION/PORO POINT LIGHTHOUSE/3',
                '/LA UNION/PORO POINT LIGHTHOUSE/4',
                '/LA UNION/PORO POINT LIGHTHOUSE/5',
                '/LA UNION/PORO POINT LIGHTHOUSE/6',
            ],
            urbiztondo_beach: [
                '/LA UNION/URBIZTONDO BEACH/1',
                '/LA UNION/URBIZTONDO BEACH/2',
                '/LA UNION/URBIZTONDO BEACH/3',
                '/LA UNION/URBIZTONDO BEACH/4',
                '/LA UNION/URBIZTONDO BEACH/5',
                '/LA UNION/URBIZTONDO BEACH/6',
                '/LA UNION/URBIZTONDO BEACH/7',
                '/LA UNION/URBIZTONDO BEACH/8',
                '/LA UNION/URBIZTONDO BEACH/9',
                '/LA UNION/URBIZTONDO BEACH/10',
            ],
            watch_tower: [
                '/LA UNION/BALUARTE WATCH TOWER/1',
                '/LA UNION/BALUARTE WATCH TOWER/2',
                '/LA UNION/BALUARTE WATCH TOWER/3',
                '/LA UNION/BALUARTE WATCH TOWER/4',
                '/LA UNION/BALUARTE WATCH TOWER/5',
                '/LA UNION/BALUARTE WATCH TOWER/6',
                '/LA UNION/BALUARTE WATCH TOWER/7',
                '/LA UNION/BALUARTE WATCH TOWER/8',
                '/LA UNION/BALUARTE WATCH TOWER/9',
                '/LA UNION/BALUARTE WATCH TOWER/10',
            ],
            immuki_island: [
                '/LA UNION/IMMUKI ISLAND/1',
                '/LA UNION/IMMUKI ISLAND/2',
                '/LA UNION/IMMUKI ISLAND/3',
                '/LA UNION/IMMUKI ISLAND/4',
                '/LA UNION/IMMUKI ISLAND/5',
                '/LA UNION/IMMUKI ISLAND/6',
                '/LA UNION/IMMUKI ISLAND/7',
            ],
            macho_temple: [
                '/LA UNION/MA-CHO TEMPLE/1',
                '/LA UNION/MA-CHO TEMPLE/2',
                '/LA UNION/MA-CHO TEMPLE/3',
                '/LA UNION/MA-CHO TEMPLE/4',
                '/LA UNION/MA-CHO TEMPLE/5',
                '/LA UNION/MA-CHO TEMPLE/6',
                '/LA UNION/MA-CHO TEMPLE/7',
            ],
            tangadan_falls: [
                '/LA UNION/TANGADAN FALLS/1',
                '/LA UNION/TANGADAN FALLS/2',
                '/LA UNION/TANGADAN FALLS/3',
                '/LA UNION/TANGADAN FALLS/4',
                '/LA UNION/TANGADAN FALLS/5',
                '/LA UNION/TANGADAN FALLS/6',
                '/LA UNION/TANGADAN FALLS/7',
                '/LA UNION/TANGADAN FALLS/8',
            ],
            pebble_beach: [
                '/LA UNION/PEBBLE BEACH/1',
                '/LA UNION/PEBBLE BEACH/2',
                '/LA UNION/PEBBLE BEACH/3',
                '/LA UNION/PEBBLE BEACH/4',
                '/LA UNION/PEBBLE BEACH/5',
                '/LA UNION/PEBBLE BEACH/6',
                '/LA UNION/PEBBLE BEACH/7',
                '/LA UNION/PEBBLE BEACH/8',
                '/LA UNION/PEBBLE BEACH/9',
                '/LA UNION/PEBBLE BEACH/10',
            ],
        },
    },
    davao: {
        main: "/aklan",
        images: {
            eden_park: [
                '/DAVAO/Eden Garden/1',
                '/DAVAO/Eden Garden/2',
                '/DAVAO/Eden Garden/3',
                '/DAVAO/Eden Garden/4',
                '/DAVAO/Eden Garden/5',
                '/DAVAO/Eden Garden/6',
                '/DAVAO/Eden Garden/7',
                '/DAVAO/Eden Garden/8',
                '/DAVAO/Eden Garden/9',
                '/DAVAO/Eden Garden/10',
            ],
            eagle_center: [
                '/DAVAO/Philippine Eagle Center/1',
                '/DAVAO/Philippine Eagle Center/2',
                '/DAVAO/Philippine Eagle Center/3',
                '/DAVAO/Philippine Eagle Center/4',
                '/DAVAO/Philippine Eagle Center/5',
            ],
            people_park: [
                '/DAVAO/People_s Park/1',
                '/DAVAO/People_s Park/2',
                '/DAVAO/People_s Park/3',
                '/DAVAO/People_s Park/4',
                '/DAVAO/People_s Park/5',
                '/DAVAO/People_s Park/6',
                '/DAVAO/People_s Park/7',
                '/DAVAO/People_s Park/8',
            ],
            jack_ridge: [
                '/DAVAO/Jack_s Ridge/1',
                '/DAVAO/Jack_s Ridge/2',
                '/DAVAO/Jack_s Ridge/3',
                '/DAVAO/Jack_s Ridge/4',
                '/DAVAO/Jack_s Ridge/5',
            ],
            crocodile_park: [
                '/DAVAO/Crocodile_s Park/1',
                '/DAVAO/Crocodile_s Park/2',
                '/DAVAO/Crocodile_s Park/3',
                '/DAVAO/Crocodile_s Park/4',
                '/DAVAO/Crocodile_s Park/5',
            ],
        },
    },
    palawan: {
        main: "/aklan",
        images: {
            puerto_princesa: [
                '/PALAWAN/Puerto Princesa/1',
                '/PALAWAN/Puerto Princesa/2',
                '/PALAWAN/Puerto Princesa/3',
                '/PALAWAN/Puerto Princesa/4',
                '/PALAWAN/Puerto Princesa/5',
                '/PALAWAN/Puerto Princesa/6',
                '/PALAWAN/Puerto Princesa/7',
            ],
            island_hopping: [
                '/PALAWAN/El Nido/1',
                '/PALAWAN/El Nido/2',
                '/PALAWAN/El Nido/3',
                '/PALAWAN/El Nido/4',
                '/PALAWAN/El Nido/5',
            ],
            coron_shipwreck: [
                '/PALAWAN/Coron Ship Wreck/1',
                '/PALAWAN/Coron Ship Wreck/2',
                '/PALAWAN/Coron Ship Wreck/3',
                '/PALAWAN/Coron Ship Wreck/4',
            ],
            honda_bay: [
                '/PALAWAN/Honda Bay/1',
                '/PALAWAN/Honda Bay/2',
                '/PALAWAN/Honda Bay/3',
                '/PALAWAN/Honda Bay/4',
                '/PALAWAN/Honda Bay/5',
            ],
            nacpan_beach: [
                '/PALAWAN/Nacpan Beach/1',
                '/PALAWAN/Nacpan Beach/2',
                '/PALAWAN/Nacpan Beach/3',
                '/PALAWAN/Nacpan Beach/4',
                '/PALAWAN/Nacpan Beach/5',
                '/PALAWAN/Nacpan Beach/6',
                '/PALAWAN/Nacpan Beach/7',
                '/PALAWAN/Nacpan Beach/8',
            ],
        },
    },
    bukidnon: {
        main: "/aklan",
        images: {
            alalumm_falls: [
                '/BUKIDNON/ALALUM FALLS/1',
                '/BUKIDNON/ALALUM FALLS/2',
                '/BUKIDNON/ALALUM FALLS/3',
                '/BUKIDNON/ALALUM FALLS/4',
                '/BUKIDNON/ALALUM FALLS/5',
                '/BUKIDNON/ALALUM FALLS/6',
                '/BUKIDNON/ALALUM FALLS/7',
                '/BUKIDNON/ALALUM FALLS/8',
                '/BUKIDNON/ALALUM FALLS/9',
                '/BUKIDNON/ALALUM FALLS/10',
                '/BUKIDNON/ALALUM FALLS/11',
            ],
            cedar_falls: [
                '/BUKIDNON/CEDAR WATERFALLS/1',
                '/BUKIDNON/CEDAR WATERFALLS/2',
                '/BUKIDNON/CEDAR WATERFALLS/3',
                '/BUKIDNON/CEDAR WATERFALLS/4',
                '/BUKIDNON/CEDAR WATERFALLS/5',
                '/BUKIDNON/CEDAR WATERFALLS/6',
                '/BUKIDNON/CEDAR WATERFALLS/7',
                '/BUKIDNON/CEDAR WATERFALLS/8',
                '/BUKIDNON/CEDAR WATERFALLS/9',
                '/BUKIDNON/CEDAR WATERFALLS/10',
                '/BUKIDNON/CEDAR WATERFALLS/11',
            ],
            communal_ranch: [
                '/BUKIDNON/COMMUNAL RANCH/1',
                '/BUKIDNON/COMMUNAL RANCH/2',
                '/BUKIDNON/COMMUNAL RANCH/3',
                '/BUKIDNON/COMMUNAL RANCH/4',
                '/BUKIDNON/COMMUNAL RANCH/5',
                '/BUKIDNON/COMMUNAL RANCH/6',
                '/BUKIDNON/COMMUNAL RANCH/7',
                '/BUKIDNON/COMMUNAL RANCH/8',
                '/BUKIDNON/COMMUNAL RANCH/9',
                '/BUKIDNON/COMMUNAL RANCH/10',
            ],
            dahilayan_park: [
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/1',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/2',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/3',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/4',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/5',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/6',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/7',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/8',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/9',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/10',
                '/BUKIDNON/DAHILAYAN ADVENTURE PARK/11',
            ],
            kaamulan_park: [
                '/BUKIDNON/KAAMULAN PARK/1',
                '/BUKIDNON/KAAMULAN PARK/2',
                '/BUKIDNON/KAAMULAN PARK/3',
                '/BUKIDNON/KAAMULAN PARK/4',
                '/BUKIDNON/KAAMULAN PARK/5',
                '/BUKIDNON/KAAMULAN PARK/6',
                '/BUKIDNON/KAAMULAN PARK/7',
                '/BUKIDNON/KAAMULAN PARK/8',
                '/BUKIDNON/KAAMULAN PARK/9',
            ],
            lake_apo: [
                '/BUKIDNON/LAKE APO/1',
                '/BUKIDNON/LAKE APO/2',
                '/BUKIDNON/LAKE APO/3',
                '/BUKIDNON/LAKE APO/4',
                '/BUKIDNON/LAKE APO/5',
                '/BUKIDNON/LAKE APO/6',
                '/BUKIDNON/LAKE APO/7',
                '/BUKIDNON/LAKE APO/8',
                '/BUKIDNON/LAKE APO/9',
                '/BUKIDNON/LAKE APO/10',
                '/BUKIDNON/LAKE APO/11',
                '/BUKIDNON/LAKE APO/12',
            ],
            monastery_transfiguration: [
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/1',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/2',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/3',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/4',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/5',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/6',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/7',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/8',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/9',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/10',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/11',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/12',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/13',
                '/BUKIDNON/MONASTARY OF TRANSFIGURATION/14',
            ],
            mt_anahawon: [
                '/BUKIDNON/MT. ANAHAWON/1',
                '/BUKIDNON/MT. ANAHAWON/2',
                '/BUKIDNON/MT. ANAHAWON/3',
                '/BUKIDNON/MT. ANAHAWON/4',
                '/BUKIDNON/MT. ANAHAWON/5',
                '/BUKIDNON/MT. ANAHAWON/6',
                '/BUKIDNON/MT. ANAHAWON/7',
                '/BUKIDNON/MT. ANAHAWON/8',
            ],
            nasuli_spring: [
                '/BUKIDNON/NASULI SPRING/1',
                '/BUKIDNON/NASULI SPRING/2',
                '/BUKIDNON/NASULI SPRING/3',
                '/BUKIDNON/NASULI SPRING/4',
                '/BUKIDNON/NASULI SPRING/5',
                '/BUKIDNON/NASULI SPRING/6',
            ],
        },
    },
    boracay: {
        main: "/aklan",
        images: {
            ariel_point: [
                '/BORACAY/ARIEL_S POINT/1',
                '/BORACAY/ARIEL_S POINT/2',
                '/BORACAY/ARIEL_S POINT/3',
                '/BORACAY/ARIEL_S POINT/4',
                '/BORACAY/ARIEL_S POINT/5',
                '/BORACAY/ARIEL_S POINT/6',
                '/BORACAY/ARIEL_S POINT/7',
                '/BORACAY/ARIEL_S POINT/8',
            ],
            bulabog_beach: [
                '/BORACAY/BULABOG BEACH/1',
                '/BORACAY/BULABOG BEACH/2',
                '/BORACAY/BULABOG BEACH/3',
                '/BORACAY/BULABOG BEACH/4',
                '/BORACAY/BULABOG BEACH/5',
                '/BORACAY/BULABOG BEACH/6',
                '/BORACAY/BULABOG BEACH/7',
                '/BORACAY/BULABOG BEACH/8',
                '/BORACAY/BULABOG BEACH/9',
            ],
            crystal_cove: [
                '/BORACAY/CRYSTAL COVE ISLAND/1',
                '/BORACAY/CRYSTAL COVE ISLAND/2',
                '/BORACAY/CRYSTAL COVE ISLAND/3',
                '/BORACAY/CRYSTAL COVE ISLAND/4',
                '/BORACAY/CRYSTAL COVE ISLAND/5',
                '/BORACAY/CRYSTAL COVE ISLAND/6',
                '/BORACAY/CRYSTAL COVE ISLAND/7',
                '/BORACAY/CRYSTAL COVE ISLAND/8',
            ],
            dmall_boracay: [
                '/BORACAY/D_MALL BORACAY/1',
                '/BORACAY/D_MALL BORACAY/2',
                '/BORACAY/D_MALL BORACAY/3',
                '/BORACAY/D_MALL BORACAY/4',
                '/BORACAY/D_MALL BORACAY/5',
                '/BORACAY/D_MALL BORACAY/6',
                '/BORACAY/D_MALL BORACAY/7',
            ],
            paraw_sailing: [
                '/BORACAY/PARAW SAILING/1',
                '/BORACAY/PARAW SAILING/2',
                '/BORACAY/PARAW SAILING/3',
                '/BORACAY/PARAW SAILING/4',
                '/BORACAY/PARAW SAILING/5',
                '/BORACAY/PARAW SAILING/6',
                '/BORACAY/PARAW SAILING/7',
                '/BORACAY/PARAW SAILING/8',
            ],
            white_beach: [
                '/BORACAY/WHITE BEACH/1',
                '/BORACAY/WHITE BEACH/2',
                '/BORACAY/WHITE BEACH/3',
                '/BORACAY/WHITE BEACH/4',
                '/BORACAY/WHITE BEACH/5',
                '/BORACAY/WHITE BEACH/6',
                '/BORACAY/WHITE BEACH/7',
                '/BORACAY/WHITE BEACH/8',
                '/BORACAY/WHITE BEACH/9',
            ],
            willys_rock: [
                '/BORACAY/WILLY_S ROCK/1',
                '/BORACAY/WILLY_S ROCK/2',
                '/BORACAY/WILLY_S ROCK/3',
                '/BORACAY/WILLY_S ROCK/4',
                '/BORACAY/WILLY_S ROCK/5',
                '/BORACAY/WILLY_S ROCK/6',
                '/BORACAY/WILLY_S ROCK/7',
            ],
        },
    },
    camiguin: {
        main: "/aklan",
        images: {
            white_island: [
                '/CAMIGUIN/WHITE ISLAND/1',
                '/CAMIGUIN/WHITE ISLAND/2',
            ],
            katibawasan_falls: [
                '/CAMIGUIN/KATIBAWASAN FALLS/1',
                '/CAMIGUIN/KATIBAWASAN FALLS/2',
                '/CAMIGUIN/KATIBAWASAN FALLS/3',
                '/CAMIGUIN/KATIBAWASAN FALLS/4',
                '/CAMIGUIN/KATIBAWASAN FALLS/5',
                '/CAMIGUIN/KATIBAWASAN FALLS/6',
                '/CAMIGUIN/KATIBAWASAN FALLS/7',
                '/CAMIGUIN/KATIBAWASAN FALLS/8',
                '/CAMIGUIN/KATIBAWASAN FALLS/9',
            ],
            sunken_cemetery: [
                '/CAMIGUIN/SUNKEN CEMETERY/1',
                '/CAMIGUIN/SUNKEN CEMETERY/2',
                '/CAMIGUIN/SUNKEN CEMETERY/3',
                '/CAMIGUIN/SUNKEN CEMETERY/4',
                '/CAMIGUIN/SUNKEN CEMETERY/5',
                '/CAMIGUIN/SUNKEN CEMETERY/6',
                '/CAMIGUIN/SUNKEN CEMETERY/7',
                '/CAMIGUIN/SUNKEN CEMETERY/8',
                '/CAMIGUIN/SUNKEN CEMETERY/9',
                '/CAMIGUIN/SUNKEN CEMETERY/10',
            ],
            mantigue_island: [
                '/CAMIGUIN/MANTIGUE ISLAND/1',
                '/CAMIGUIN/MANTIGUE ISLAND/2',
                '/CAMIGUIN/MANTIGUE ISLAND/3',
                '/CAMIGUIN/MANTIGUE ISLAND/4',
                '/CAMIGUIN/MANTIGUE ISLAND/5',
                '/CAMIGUIN/MANTIGUE ISLAND/6',
                '/CAMIGUIN/MANTIGUE ISLAND/7',
                '/CAMIGUIN/MANTIGUE ISLAND/8',
                '/CAMIGUIN/MANTIGUE ISLAND/9',
            ],
            bura_water_park: [
                '/CAMIGUIN/BURA SODA WATER PARK/1',
                '/CAMIGUIN/BURA SODA WATER PARK/2',
                '/CAMIGUIN/BURA SODA WATER PARK/3',
                '/CAMIGUIN/BURA SODA WATER PARK/4',
                '/CAMIGUIN/BURA SODA WATER PARK/5',
                '/CAMIGUIN/BURA SODA WATER PARK/6',
                '/CAMIGUIN/BURA SODA WATER PARK/7',
            ],
            tanguines_lagoon: [
                '/CAMIGUIN/TANGUINES LAGOON/1',
                '/CAMIGUIN/TANGUINES LAGOON/2',
                '/CAMIGUIN/TANGUINES LAGOON/3',
                '/CAMIGUIN/TANGUINES LAGOON/4',
                '/CAMIGUIN/TANGUINES LAGOON/5',
                '/CAMIGUIN/TANGUINES LAGOON/6',
                '/CAMIGUIN/TANGUINES LAGOON/7',
            ],
        },
    },
    panabo: {
        main: "/aklan",
        images: {
            japanese_tunnel: [
                '/PANABO/JAPANESE TUNNEL/1',
                '/PANABO/JAPANESE TUNNEL/2',
                '/PANABO/JAPANESE TUNNEL/3',
                '/PANABO/JAPANESE TUNNEL/4',
                '/PANABO/JAPANESE TUNNEL/5',
                '/PANABO/JAPANESE TUNNEL/6',
                '/PANABO/JAPANESE TUNNEL/7',
                '/PANABO/JAPANESE TUNNEL/8',
            ],
            mangrove_forest: [
                '/PANABO/MANGROVE FOREST BOARDWALK/1',
                '/PANABO/MANGROVE FOREST BOARDWALK/2',
                '/PANABO/MANGROVE FOREST BOARDWALK/3',
                '/PANABO/MANGROVE FOREST BOARDWALK/4',
                '/PANABO/MANGROVE FOREST BOARDWALK/5',
                '/PANABO/MANGROVE FOREST BOARDWALK/6',
                '/PANABO/MANGROVE FOREST BOARDWALK/7',
                '/PANABO/MANGROVE FOREST BOARDWALK/8',
            ],
            seawall: [
                '/PANABO/SEAWALL/1',
                '/PANABO/SEAWALL/2',
                '/PANABO/SEAWALL/3',
                '/PANABO/SEAWALL/4',
                '/PANABO/SEAWALL/5',
                '/PANABO/SEAWALL/6',
                '/PANABO/SEAWALL/7',
                '/PANABO/SEAWALL/8',
                '/PANABO/SEAWALL/9',
            ],
        },
    },
    tagum: {
        main: "/aklan",
        images: {
            botanical_park: [
                '/TAGUN/BOTANICAL PARK/1',
                '/TAGUN/BOTANICAL PARK/2',
                '/TAGUN/BOTANICAL PARK/3',
                '/TAGUN/BOTANICAL PARK/4',
                '/TAGUN/BOTANICAL PARK/5',
                '/TAGUN/BOTANICAL PARK/6',
                '/TAGUN/BOTANICAL PARK/7',
                '/TAGUN/BOTANICAL PARK/8',
                '/TAGUN/BOTANICAL PARK/9',
                '/TAGUN/BOTANICAL PARK/10',
                '/TAGUN/BOTANICAL PARK/11',
            ],
            banana_beach: [
                '/TAGUN/BANANA BEACH/1',
                '/TAGUN/BANANA BEACH/2',
                '/TAGUN/BANANA BEACH/3',
                '/TAGUN/BANANA BEACH/4',
                '/TAGUN/BANANA BEACH/5',
                '/TAGUN/BANANA BEACH/6',
            ],
            nabintad_cruise: [
                '/TAGUN/NABINTAD RIVER CRUISE/1',
                '/TAGUN/NABINTAD RIVER CRUISE/2',
                '/TAGUN/NABINTAD RIVER CRUISE/3',
                '/TAGUN/NABINTAD RIVER CRUISE/4',
                '/TAGUN/NABINTAD RIVER CRUISE/5',
                '/TAGUN/NABINTAD RIVER CRUISE/6',
                '/TAGUN/NABINTAD RIVER CRUISE/7',
                '/TAGUN/NABINTAD RIVER CRUISE/8',
            ],
        },
    },
}